#PLAYBOOK
---
#PLAY
- name: samba
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #RUN APT INSTALL SAMBA
    - name: install samba
      #ACTION
      apt:
        name: ['samba']
        state: latest
    #CREATE SHARED DIRECTORY
    - name: create a public read only directory
      #ACTION
      file:
        path: /home/vagrant/public/
        state: directory
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"
    #PUT  arquivoImportante.txt INSIDE THE SHARED DIRECTORY
    - name: send arquivoImportante.txt
      copy:
        src: ./arquivoImportante.txt
        dest: /home/vagrant/public/
        mode: '0766'
        owner: "vagrant"
        group: "vagrant"

    - name: create group employees
      group:
        name: employees
        state: present
    
    - name: create employee user
      user:
        name: employee
        group: employees

    - name: create an employees only directory
      file:
        path: /home/vagrant/employees/
        state: directory
        mode: '0770'
        owner: "root"
        group: "employees"

    - name: add employees directory to samba config
      blockinfile:
        path:  /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [employees]
            path = /home/vagrant/employees
            valid users = @employees
            read only = no
            browsable = yes
          [public]
            path = /home/vagrant/public/
            read only = yes
            browsable = yes
      notify: restart samba

    - name: set Samba passwords for each user
      shell: "{{ item }}"
      with_items:
        - printf '123\n123\n' | smbpasswd -a vagrant
        - printf '1234\n1234\n' | smbpasswd -a employee
  handlers:
    #RESTART NGINX SERVICE
    - name: restart samba
      service:
        name: smbd
        state: restarted