#PLAYBOOK
---
#PLAY
- name: samba
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #RUN APT INSTALL SAMBA
    - name: install samba
      #ACTION
      apt:
        name: ['samba']
        state: latest
    #CREATE SHARED DIRECTORY
    - name: create shared directory
      #ACTION
      file:
        path: /home/vagrant/samba/
        state: directory
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"
    #PUT  arquivoImportante.txt INSIDE THE SHARED DIRECTORY
    - name: send arquivoImportante.txt
      copy:
        src: ./arquivoImportante.txt
        dest: /home/vagrant/samba/
        mode: '0766'
        owner: "vagrant"
        group: "vagrant"
    #ADD SHARED DIRECTORY TO THE SAMBA CONFIG
    - name: add shared directory config
      #ACTION
      blockinfile:
        path:  /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [samba]
            comment = Samba on Ubuntu
            path = /home/vagrant/samba
            read only = yes
            browsable = yes
      notify: restart samba
    #DEFINE SAMBA USER
    - name: set Samba passwords for each user
      #ACTION
      shell: "printf '123\n123\n' | smbpasswd -a vagrant"
  handlers:
    #RESTART NGINX SERVICE
    - name: restart samba
      service:
        name: smbd
        state: restarted