---
- name: samba
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install samba
      apt:
        name: ['samba']
        state: latest

    - name: Copy samba configuryation file
      copy:
        src: smb.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'

    - name: create a public read only directory
      file:
        path: /home/vagrant/public/
        state: directory
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"

    - name: send arquivoImportante.txt
      copy:
        src: ./arquivoImportante.txt
        dest: /home/vagrant/public/
        mode: '0766'
        owner: "vagrant"
        group: "vagrant"

    - name: create group employees
      group:
        name: employees
        state: present
    
    - name: create employee user
      user:
        name: employee
        group: employees

    - name: create an employees only directory
      file:
        path: /home/vagrant/employees/
        state: directory
        mode: '0770'
        owner: "root"
        group: "employees"

    - name: set Samba passwords for each user
      shell: "{{ item }}"
      with_items:
        - printf '123\n123\n' | smbpasswd -a vagrant
        - printf '1234\n1234\n' | smbpasswd -a employee
        - pdbedit -P "min password length" -C 8
        - pdbedit -P "maximum password age" -C 604800
        - pdbedit -P "bad lockout attempt" -C 3
  handlers:
    #RESTART NGINX SERVICE
    - name: restart samba
      service:
        name: smbd
        state: restarted