
---

- name: proxy
  hosts: all
  gather_facts: false
  become: true
  vars:
    squid_port: 3128
    localnet: 192.168.0.0/24
  tasks:
    - name: install squid
      apt:
        name: ['squid']
        state: present
      notify: restart squid

    - name: Copy regex list
      copy: 
        src: regex.lst
        dest: /etc/squid/ 
        owner: root
        group: root
        mode: '0644'
      notify: restart squid

    - name: Copy unproductive sites list
      copy: 
        src: unproductiveSites.lst
        dest: /etc/squid/ 
        owner: root
        group: root
        mode: '0644'
      notify: restart squid
    
    - name: Copy squid configuryation file
      copy:
        src: squid.conf
        dest: /etc/squid/squid.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart squid
  handlers:
    #RESTART SQUID SERVICE
    - name: restart squid
      service:
        name: squid
        state: restarted