#PLAYBOOK
---
#PLAY
- name: ftp
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
  #INSTALL FTP SERVER
    - name: install vsftpd
      become: yes
      apt:
        name: vsftpd
        state: present
      notify: restart vsftp
    #MOVE THE SERVER CONFIGURATION FILE
    - name: move config file          
      become: yes
      copy:
        src: ./vsftpd.conf            
        dest: /etc/vsftpd.conf
      notify: restart vsftp

    #CREATE A LOGIN USER TO THE SERVER
    - name: create a login user
      become: yes
      user:
        name: teste
        password: "$6$vOBO1TyfSTrtR$zq9vCB2EsfOWs0pIo4hhsbEO1DlfGhVWNu7ZSoWcfX3ntvZ6YfzHRBgMaPDmhqWa07jNg2IQRUcKy7tAEim5G0"
      notify: restart vsftp

    - name: Creating users teste2
      user:
        name: teste2
        password: "$6$Yfc9la.SqvhtwXaz$1ZAt0/9TwDTwlOfokWMkTxBIARzbbBfbHGOVg1cm2Gsr2DPlUgI2J52gMsHZwWH02phvat5YjLTBNGKSAS3Nu1"
  handlers:
  #RESTART VSFTP SERVICE
  - name: restart vsftp
    service:
      name: vsftpd
      state: restarted