---
- name: firewall
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: enable UFW
      ufw:
        state: enabled
        policy: allow
      notify: restart ufw

    - name: Deny torrent related ports
      ufw:
        rule: deny
        port: "6881:6889"
        proto: "{{ item }}"
      notify: restart ufw
      with_items:
        - tcp
        - udp
    
    - name: Deny access to port 80 from public network
      ufw:
        rule: deny
        from_ip: 192.168.0.0/21
        port: "80"
        proto:  "{{ item }}"
      notify: restart ufw
      with_items:
        - tcp
        - udp

    - name: Deny outgoing ssh connections
      ufw:
        rule: deny
        port: "22"
        proto: "{{ item }}"
        direction: out
      with_items:
        - tcp
        - udp
  handlers:
    - name: restart ufw
      service:
        name: ufw
        state: restarted