---
- name: firewall
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow
    - name: Deny torrent related ports
      ufw:
        rule: deny
        port: "6881:6889"
        proto: tcp
      notify: restart ufw
  handlers:
    - name: restart ufw
      service:
        name: ufw
        state: restarted