#PLAYBOOK
---
#PLAY
- name: nginx
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #ENABLE FIREWALL ALLOWING EVERYTHING
    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow
    #ALLOW ACCESS ON PORT 80, ALLOWING HTTP TRAFFIC
    - name: Allow http traffic
      ufw:
        rule: allow
        port: 80
        proto: tcp