#PLAYBOOK
---
#PLAY
- name: nginx
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #ENABLE FIREWALL ALLOWING EVERYTHING
    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow
    #ALLOW ACCESS ON PORT 22, ALLOWING ACCESS VIA SSH
    - name: Allow ssh access
      ufw:
        rule: allow
        port: 22
        proto: tcp