#PLAYBOOK
---
#PLAY
- name: nginx
  hosts: all
  gather_facts: false
  become: true
  vars:
    mysql_root_password: password
    ansible_python_interpreter: /usr/bin/python3
  #TASKS  
  tasks:
    #INSTALL MYSQL
    - name: install mysql
      apt:
        name:   ['mysql-server']
        state:  latest
      notify: restart mysql
    #INSTALL NEEDED PYTHON PACKAGES
    - name: install python related packages
      apt:
        name: ['python3-mysqldb', 'python3-pip', 'python3-pymysql']
        state: present
    #COPY THE MYSQL CONF FILE TO REMOTE HOST
    - name: Copy the my.cnf
      copy: 
        src: my.cnf 
        dest: /root/.my.cnf 
        owner:  root 
        mode: 0600
    #UPDATE THE PASSWORD FOR THE ROOT USER
    - name: Update MySQL Root Password
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root 
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
      notify: restart mysql
    #CREATE A NEW DATABASE CALLED TEST
    - name: create new database
      mysql_db:
        name: test
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
  handlers:
    #RESTART MYSQL SERVICE
    - name: restart mysql
      service:
        name: mysql
        state: restarted