#PLAYBOOK
---
#PLAY
- name: nginx
  hosts: all
  gather_facts: false
  become: true
  vars:
    mysql_root_password: senha123!
  #TASKS  
  tasks:
    #INSTALL MYSQL
    - name: install mysql
      apt:
        name:   ['mysql-server']
        state:  latest
      notify: restart mysql
    #SET THE PASSWORD FOR THE MYSQL ACCOUNTS
    # - name: update mysql root password for all root accounts
    #   mysql_user:
    #     name: root
    #     host: "{{ item }}"
    #     password: "{{ mysql_root_password }}"
    #     login_user: root
    #     login_password: "{{ mysql_root_password }}"
    #     check_implicit_admin: yes
    #     priv: "*.*:ALL, GRANT"
    #   with_items:
    #   - 127.0.0.1
    #   - ::1
    #   - localhost
    #   notify: restart mysql
  handlers:
    #RESTART MYSQL SERVICE
    - name: restart mysql
      service:
        name: mysql
        state: restarted