#PLAYBOOK
---
#PLAY
- name: nginx
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #RUN APT UPDATE
    - name: apt update
      #ACTION
      apt:  update_cache=yes
            force_apt_get=yes
            cache_valid_time=3600
    #RUN APT UPGRADE
    - name: apt upgrade
      #ACTION
      apt:  upgrade=dist
            force_apt_get=yes
            #RUN APT INSTALL NGINX
    #INSTALL NEEDED PYTHON PACKAGES
    - name: install python related packages
      apt:
        name: ['python3-mysqldb', 'python3-pip', 'python3-pymysql']
        state: present
    - name: install nginx
      #ACTION
      apt:
        name:   ['nginx']
        state:  latest
    #CREATE FOLDER avaliacao3.com ON /var/www/ INSIDE THE BOX
    - name: create www directory
      #ACTION
      copy:
        src:  ./avaliacao3.com
        dest: /var/www/
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"
    #DELETE THE DEFAULT NGINX SITE CONFIGURATION
    - name: delete default nginx site
      #ACTION
      file:
        path: /etc/nginx/sites-available/default
        state: absent
      notify: restart nginx
    #CREATE THE SITE CONFIGURATION (nginx.conf.j2) TO SERVE WHATS INSIDE /var/www/avaliacao3.com
    - name: copy nginx site.conf
      #ACTION
      ansible.builtin.copy:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx
  handlers:
    #RESTART NGINX SERVICE
    - name: restart nginx
      service:
        name: nginx
        state: restarted